### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by CodyPChristian** [howiemnet/MotionControl#1]
Hey, great work on this! Surprised that more people are not doing stuff like this! Any idea if you will ever update this to work with todays SDKs? Also where could I find your code for Arduino / Processing and Blender? Thanks

**Comment by howiemnet** [comment]
Unlikely to have time to revisit this for a while I'm afraid... but there's Teensy code (which I put together in the Arduino IDE - should be adaptable to Atmegas reasonably easily as long as it'll run fast enough) and a bit of Python for Blender linked from the main readme file. Sorry I haven't better news :)
