### ISSUE TITLE
Frame sync / genlock of Canon EOS cameras

### ISSUE THREAD

**Issue by vonj** [howiemnet/MotionControl#2]
Hi!

Did you find a way to genlock video / frame sync out with Magic Lantern? 

If not, how can your mo-co video look so damn _good_?

**Comment by howiemnet** [comment]
Nope - but while chatting with a guy in the mo-co industry, I found out that it barely (if ever) gets used.   It's only of any relevance if you're trying to do multiple passes, filming the same camera move multiple times so you can comp them together - say you want the same actor in two different places in the scene simultaneously. If you're doing stop-motion, the frames will match perfectly anyway, as you wait for the rig to finish moving, then you click the shutter. And if the camera's moving, the maximum error between shots will be half a frame, which is pretty much invisible for slower shots. For faster shots, you can interpolate the footage to a much higher frame rate using AE or Twixtor etc, then slip the footage forwards or backwards until it matches.

There's only one real shot in my vid that uses multiple passes: the final poker-chip one, where it starts with full-motion, then transitions into stop-motion, then back into full-motion again: even though there was no shutter-sync going on, the transitions are seamless. There just isn't enough motion to make any half-a-frame error actually visible.

So thankfully it's not necessary. Glad you liked my vid though. Thanks! :)
